run_task_1:
	python test_hopfield.py --patterns_no 2 --train_lr 0.1 --task 1 --patterns_width 50 --patterns_height 50

run_task_2:
	python test_hopfield.py --patterns_no 10 --noise 0.15 --task 2 --patterns_width 25 --patterns_height 25

run_task_3:
	python test_hopfield.py --task 3 --patterns_no 10

run_task_4:
	python test_hopfield.py --task 4 --patterns_no 200 --unlearn_no 50 --unlearn_lr 0.05